#!/bin/bash
USERNAME=$1
DIR=/git/users/$USERNAME

set -e

cd "$DIR/repo.git"
sudo -u "$USERNAME" git log --graph --all --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --abbrev-commit --date=relative


